name: flex
description: A collection of classes, extensions and utilities to aid faster development.
version: 0.4.0
homepage: https://github.com/pfaffdev/flex
issue_tracker: https://github.com/pfaffdev/flex/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  intl: ^0.16.0
  io: ^0.3.3
  meta: ^1.1.8
  rxdart: ^0.23.1
  tuple: ^1.0.3
 
dev_dependencies:
  test: ^1.9.4
